name: fly_cargo
description: "Sapsano"
publish_to: "none"

version: 1.0.0+10

environment:
  sdk: ">=3.10.0 <4.0.0"

analyzer:
  enable-experiment:
    - dot-shorthands

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  yandex_maps_mapkit_lite: ^4.29.0-beta
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  get_it: ^9.2.0
  injectable: ^2.7.1+4
  shared_preferences: ^2.5.4
  equatable: ^2.0.8
  image_picker: ^1.2.1
  flutter_image_compress: ^2.3.0
  freezed_annotation: ^3.0.0
  heroicons: ^0.11.0
  intl: ^0.20.2
  package_info_plus: ^9.0.0
  google_fonts: ^8.0.0
  go_router: ^17.0.1
  webview_flutter: ^4.13.1
  haptic_feedback: ^0.6.4+3
  firebase_core: ^4.4.0
  firebase_app_check: ^0.4.1+4
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  pretty_dio_logger: ^1.4.0
  flutter_multi_formatter: ^2.13.10
  flutter_markdown: ^0.7.7+1
  url_launcher: ^6.3.2
  mobile_scanner: ^7.1.4
  mockito: ^5.6.3
  bloc_test: ^10.0.0
  sentry_flutter: ^9.10.0
  sentry_dio: ^9.10.0
  uuid: ^4.5.2
  firebase_analytics: ^12.1.1
  firebase_crashlytics: ^5.0.7
  firebase_performance: ^0.11.1+4
  firebase_remote_config: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/videos/

