name: fly_cargo
description: "Sapsano"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.10.0 <4.0.0"

analyzer:
  enable-experiment:
    - dot-shorthands

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
#  yandex_maps_mapkit_lite: ^4.29.0-beta
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  http: ^1.2.2
  http_parser: ^4.0.2
  talker_flutter: ^5.0.2
  talker: ^5.0.2
  talker_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  get_it: ^8.2.0
  injectable: ^2.5.2
  shared_preferences: ^2.5.3
  retrofit: ^4.6.0
  equatable: ^2.0.5
  image_picker: ^1.1.2
  flutter_image_compress: ^2.3.0
  freezed_annotation: ^3.0.0
  heroicons: ^0.11.0
  intl: ^0.20.2
  package_info_plus: ^8.0.0
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1
  video_player: ^2.10.1
  go_router: ^14.6.0
  webview_flutter: ^4.10.0
  haptic_feedback: ^0.6.4+3
  firebase_core: ^4.3.0
  firebase_app_check: ^0.4.1+3
  dio_cookie_manager: ^3.3.0
  cookie_jar: ^4.0.8
  pretty_dio_logger: ^1.4.0
  flutter_multi_formatter: ^2.13.10
  flutter_markdown: ^0.7.4+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^10.0.6
  freezed: ^3.2.3

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/videos/

