name: fly_cargo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  yandex_maps_mapkit_lite: ^4.19.0-beta
  flutter_bloc: ^9.1.1
  json_annotation: ^4.9.0
  dio: ^5.9.0
  talker_flutter: ^5.0.2
  talker: ^5.0.2
  talker_logger: ^5.0.2
  talker_bloc_logger: ^5.0.2
  talker_dio_logger: ^5.0.2
  get_it: ^8.2.0
  injectable: ^2.5.2
  shared_preferences: ^2.5.3
  html: ^0.15.4
  retrofit: ^4.6.0
  logger: ^2.6.0
  equatable: ^2.0.5
  flutter_better_auth: ^0.1.3
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  json_serializable: ^6.11.1
  build_runner: ^2.4.13
  injectable_generator: ^2.6.2
  retrofit_generator: ^10.0.6

flutter:
  uses-material-design: true

  assets:
    - assets/images/
